---
title: "Preface"
---

This document has been produced to guide analysts through the use of statistical analyses in Info Delivery; it spares details on statistical theory and predominantly focuses on key, actionable steps from how to decide on which statistical test(s) to use, to getting the results of that test displayed in a Power BI visual. Thus, there is little information included within here on how exactly each test works from a statistical perspective, nor exactly how the values from a test should be interpreted (but see below). Nonetheless, it is generally recommended that whenever using any statistical test, you consult external resources (e.g. Stack Overflow, R bloggers) that help gauge an understanding of what your statistical test is asking of the data and what the results mean within that context.

### Significance Testing

This guide predominantly focuses on null hypothesis significance testing, meaning that ‘significant results’ are interpreted as being below a p-value of 0.05. Simply put, these p-values are a numerical representation of your degree of confidence in the result of a test, as it is the probability that you could have attained those results purely by chance. Thus, it is always worth considering that this 0.05 threshold is somewhat arbitrary, and the probability of having attained a result being 0.049 versus 0.051 should not necessarily lead to a wildly different interpretation. P-values are therefore often criticized (despite their ongoing, widespread use) and this should be considered when interpreting the results of a statistical test (see [(176) P-values Broke Scientific Statistics—Can We Fix Them? - YouTube](https://www.youtube.com/watch?v=tLM7xS6t4FE) for a simple explanation of p-value criticisms). In line with these criticism, it is worth considering that the great number of analyses you run on the same set of data, the more likely it is that you encounter a significant result by chance (e.g. a false positive); in which case, consider implementing a multiple-comparison correction (e.g. Bonferroni test). Finally, while we have generally endeavored to categorise each statistical test's assumptions concisely this could sometimes lead to an oversimplification of a given test (e.g. some 'parametric tests' are more robust to non-normality that others). Again, reading around the statistical test that you select is generally advised.